# Generated by Django 4.0.6 on 2022-08-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Description', models.TextField()),
                ('gh_link', models.CharField(max_length=200)),
                ('live_link', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
