# Generated by Django 4.0.6 on 2022-08-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='fullstack', max_length=150),
            preserve_default=False,
        ),
    ]
